// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAzaHsHsmpYh8BKx-hVCh53S-gNyUEViY',
    appId: '1:57193616084:web:44c025d325b0da48ff6141',
    messagingSenderId: '57193616084',
    projectId: 'veresiyeapp-8edc6',
    authDomain: 'veresiyeapp-8edc6.firebaseapp.com',
    storageBucket: 'veresiyeapp-8edc6.firebasestorage.app',
    measurementId: 'G-47Z442MC33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDqOe7YuP8XWKfMkVJvS1FzfJIt3Xz96g',
    appId: '1:57193616084:android:a2c005d3b2575152ff6141',
    messagingSenderId: '57193616084',
    projectId: 'veresiyeapp-8edc6',
    storageBucket: 'veresiyeapp-8edc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClFpJ-O5B15S96CRcyCF6CVx0oL9ghBGA',
    appId: '1:57193616084:ios:e9623d728f276a8eff6141',
    messagingSenderId: '57193616084',
    projectId: 'veresiyeapp-8edc6',
    storageBucket: 'veresiyeapp-8edc6.firebasestorage.app',
    iosBundleId: 'com.example.veresiyeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClFpJ-O5B15S96CRcyCF6CVx0oL9ghBGA',
    appId: '1:57193616084:ios:e9623d728f276a8eff6141',
    messagingSenderId: '57193616084',
    projectId: 'veresiyeapp-8edc6',
    storageBucket: 'veresiyeapp-8edc6.firebasestorage.app',
    iosBundleId: 'com.example.veresiyeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAzaHsHsmpYh8BKx-hVCh53S-gNyUEViY',
    appId: '1:57193616084:web:1318ea6a27c1aa9bff6141',
    messagingSenderId: '57193616084',
    projectId: 'veresiyeapp-8edc6',
    authDomain: 'veresiyeapp-8edc6.firebaseapp.com',
    storageBucket: 'veresiyeapp-8edc6.firebasestorage.app',
    measurementId: 'G-36TVXYEHP6',
  );
}
